server:
  port: 8080
  
logging:
  level: "info"
  
pubsub:
  project_id: "glo-isg-reloads-project-dev"
  subscription: "glo-isg-dodrio-d-notification-subscription-ddr-762"

sms-notification:
 SEND_SMS_NOTIFICATION_URL: "https://dodrio-dev.globetel.com/integration-services/data-builder/mock/notifications"
 SEND_SMS_NOTIFICATION_X_API_KEY: ""


