server:
  port: 8084

logging:
  level: "info"

pubsub:
  project_id: "local-dodrio-project"
  subscription: "glo-isg-dodrio-d-notification-subscription-ddr-762"

sms-notification:
  send_sms_notification_url: "http://wiremock:8080/apigw/sit5/dodrio/ws/soap12/apikey_auth/notif"
  send_sms_notification_x_api_key: ""
